### PR TITLE
Remove use of custom question type

### PR DESCRIPTION
**Pull request by inducer**
@dzhuang Especially in light of the discussion in https://github.com/inducer/relate/issues/243, I'm thinking of deprecating and eventually removing the possibility of having user-custom question types with code running at the privilege level of the app server. How do you feel about this?

### CODE REVIEW

**Comment by dzhuang** [comment]
I agree.  I think the following need to be done:

1. Instance owner can have their own built-in page types other than what were allowed in `course.page`.
1. Instance owner can define a deadline in settings when custom pages are not allowed any longer.
1. Backward compatibility is needed for existing page.

**Comment by inducer** [comment]
> Instance owner can define a deadline in settings when custom pages are not allowed any longer.

That's a good idea.

**Comment by dzhuang** [comment]
I think instead of removing custom pages from the repo, keeping it in repo is good for tests. For example, test whether the repo will pass validation when passing deadline.

**Comment by dzhuang** [comment]
However, we need to add some warning literals in the custom pages (no only validation warning).

**Comment by inducer** [comment]
> I think instead of removing custom pages from the repo, keeping it in repo is good for tests. For example, test whether the repo will pass validation when passing deadline.

We can just keep this version on a branch (say `with-deprecated-custom-question`).

**Comment by inducer** [comment]
> However, we need to add some warning literals in the custom pages (no only validation warning).

Not sure I understand what you mean here.

**Comment by inducer** [comment]
Is this OK to merge from your end?

**Comment by dzhuang** [comment]
> We can just keep this version on a branch (say with-deprecated-custom-question).

I agree. So "update course content" from branch commits can be tested.

>> However, we need to add some warning literals in the custom pages (no only validation warning).

> Not sure I understand what you mean here.

I meant to add warning in the body of the custom page.

**Comment by dzhuang** [comment]
> Is this OK to merge from your end?

Ok.

**Comment by inducer** [comment]
Thx! In it goes.

**Comment by inducer** [comment]
https://github.com/inducer/relate-sample/tree/with-deprecated-custom-question

**Comment by dzhuang** [comment]
Got it. Thanks.

**Pull request merged**
